FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y \
    mariadb-server \
    mariadb-client && \
    rm -rf /var/lib/apt/lists/*

COPY config/99-inception.cnf /etc/mysql/mariadb.conf.d/99-inception.cnf

COPY tools/setup.sh /setup.sh
RUN chmod +x /setup.sh

ENTRYPOINT [ "/setup.sh" ]