FROM debian:bullseye

RUN apt update && \
    apt install -y \
    mariadb-server \
    mariadb-client

RUN sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' \
    /etc/mysql/mariadb.conf.d/50-server.cnf

COPY tools/setup.sh /setup.sh
RUN chmod +x /setup.sh

ENTRYPOINT [ "/setup.sh" ]