FROM debian:bullseye

RUN apt update && \
    apt install -y \
    curl \
    php7.4 \
    php7.4-fpm \
    php7.4-mysql \
    mariadb-client
    
RUN curl -o latest.tar.gz https://wordpress.org/latest.tar.gz && \
    tar -xzf latest.tar.gz && rm latest.tar.gz
RUN mkdir -p /var/www/html && mv wordpress/* /var/www/html/ && \
    rm -rf wordpress latest.tar.gz

#wp-cli moment
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

#setting port on 9000
RUN sed -i 's|listen = .*|listen = 9000|' \
    /etc/php/7.4/fpm/pool.d/www.conf

#less trash output
RUN ln -s /bin/true /usr/sbin/sendmail

COPY tools/init.sh /init.sh
RUN chmod +x /init.sh
CMD [ "/init.sh" ]