FROM debian:bookworm

RUN apt update && apt install -y nginx openssl

COPY conf/nginx.conf /etc/nginx/nginx.conf

COPY tools/create_cert.sh /tmp/create_cert.sh
RUN chmod +x /tmp/create_cert.sh && /tmp/create_cert.sh

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]